[project]
name = "kor-eng-converter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pyautogui>=0.9.54",
    "pyinstaller>=6.13.0",
    "pyperclip>=1.9.0",
]
